### ISSUE TITLE
command to reload the config file

### ISSUE THREAD

**Issue by jduepmeier** [fsmi/rpcd#22]
Enable a command to reload the config file.

**Comment by cbdevnet** [comment]
Will be implemented by handling `SIGHUP`

**Comment by cbdevnet** [comment]
The straightforward way to implement this would be to call all module cleanup functions (releasing all module-local storage), then run the configuration parser again (re-allocating all state). This is only possible when no commands (and, later, windows) are running, as their state tracking data will be `free`d by the cleanup functions.

Thus
* Sending `SIGHUP` will set a `reload requested` flag
* As soon as all user commands are stopped, all automated windows will be terminated, all module cleanup procedures will then be called, followed by the configuration parser. This allows a graceful reload without interrupting user experience
* The `reload requested` flag will then be reset
* Configured automation will be executed

When receiving a second `SIGHUP` before the first one is handled, all user commands will be terminated and the reload will be handled immediately (that is, in the `select` iteration interrupted by the signal).
